### PR TITLE
Bump Chef version to 12 and bump knife

### PR DESCRIPTION
**Pull request by michiels**
This updates the gems in our Gemfile to the latest versions.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Can you add a changelog entry?

**Comment by jvanbaarsen** [comment]
Also, did you test in combination with Intercity?

**Comment by michiels** [comment]
@jvanbaarsen I tested it locally with the included tests and Vagrant of chef-repo itself. Not sure if we need to test it with our Intercity app at this moment. I think we need to test the Intercity app when we decide that we want to use this newest version of the chef-repo, right?

**Comment by jvanbaarsen** [comment]
@michiels :+1! Squash and merge :-)

**Pull request merged**
